apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - image: dpage/pgadmin4
          name: pgadmin4
          envFrom:
            - secretRef:
                name: pgadmin-secrets
            
