apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:15.1-alpine
          name: postgres
          envFrom:
            - secretRef:
                name: postgres-secrets
