apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui

spec:
  selector:
    matchLabels:
      app: ui

  template:
    metadata:
      name: ui
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: mstarski/ui
          envFrom:
            - configMapRef:
                name: ui-env
            
  replicas: 3
